package com.knowledge.acquisition.entity;

import com.knowledge.acquisition.config.VectorType;
import jakarta.persistence.*;
import java.util.UUID;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Type;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity representing a single step within a workflow in the knowledge graph.
 *
 * <p>This entity maps to the knowledge.knowledge_workflow_steps table and stores atomic actions or
 * decision points within business processes. Each step captures the actor, action performed,
 * input/output parameters, and sequencing information.
 *
 * <p><strong>Database Constraints:</strong>
 *
 * <ul>
 *   <li>project_id: NOT NULL - must be inherited from parent workflow before persistence
 *   <li>workflow_id: NOT NULL - links step to its parent workflow
 * </ul>
 *
 * @see com.knowledge.acquisition.dto.KnowledgeWorkflowStep
 * @see WorkflowEntity
 */
@Entity
@Table(name = "knowledge_workflow_steps", schema = "knowledge")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WorkflowStepEntity {
  /** Primary key - uniquely identifies this workflow step */
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  @Column(name = "step_id")
  private UUID stepId;

  /**
   * Project identifier that owns this workflow step.
   *
   * <p><strong>NOT NULL constraint</strong> - must be set before saving to database. Typically
   * inherited from parent workflow via KnowledgeGraphService.
   */
  @Column(name = "project_id", nullable = false)
  private UUID projectId;

  /**
   * Foreign key to parent workflow.
   *
   * <p><strong>NOT NULL constraint</strong> - every step must belong to a workflow.
   */
  @Column(name = "workflow_id", nullable = false)
  private UUID workflowId;

  /** Order of this step within the workflow (1-based sequence) */
  @Column(name = "sequence_number")
  private Integer sequenceNumber;

  /**
   * Person, role, or system responsible for executing this step.
   *
   * <p>Examples: "Customer Service Rep", "Payment Gateway", "System Admin"
   */
  @Column(name = "actor", columnDefinition = "text")
  private String actor;

  /**
   * Description of the action performed in this step.
   *
   * <p>Stored as PostgreSQL TEXT to accommodate detailed action descriptions.
   */
  @Column(name = "action_text", columnDefinition = "text")
  private String actionText;

  /**
   * JSON structure containing input parameters for this step.
   *
   * <p>Stored as PostgreSQL JSONB for efficient querying and indexing.
   */
  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "input_parameters", columnDefinition = "jsonb")
  private String inputParameters;

  /**
   * JSON structure containing output parameters produced by this step.
   *
   * <p>Stored as PostgreSQL JSONB for efficient querying and indexing.
   */
  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "output_parameters", columnDefinition = "jsonb")
  private String outputParameters;

  /**
   * JSON structure containing business rules applicable to this step.
   *
   * <p>Stored as PostgreSQL JSONB for efficient querying and indexing.
   */
  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "business_rules", columnDefinition = "jsonb")
  private String businessRules;

  /**
   * Vector embedding for semantic similarity search (768-dimensional).
   *
   * <p>Generated by Vertex AI embedding service and stored using pgvector extension. Used for
   * finding semantically similar workflow steps across the knowledge graph.
   */
  @Column(name = "embedding")
  @Type(VectorType.class)
  private String embedding;
}
